# .github/workflows/enforce-checklist.yml
name: Enforce Checklist

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  enforce-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Required Checklist
        id: checklist
        run: |
          # Define the required checklist items
          required_items=("Are your changes following SOLID principles?" "Are there any erroneous console logs, debuggers or leftover code in your changes?" "Walk away, take a break, re-read what you filled out above does it make sense if you were coming in cold? What extra context could you provide?")
          
          # Read the PR description
          pr_description=$(jq -r .pull_request.body $GITHUB_EVENT_PATH)
          
          # Check if all required items are checked in the PR description
          invalid_items=false
          for item in "${required_items[@]}"; do
            if [[ ! "$pr_description" =~ "- [x] $item" ]]; then
              invalid_items=true
              echo "Unchecked checklist item: $item"
            fi
          done
          
          # Output the result
          echo "::set-output name=invalidItems::$invalid_items"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Check Status
        if: steps.checklist.outputs.invalidItems == 'true'
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/check-runs" \
            -d "{\"name\":\"Checklist\",\"head_sha\":\"${{ github.event.pull_request.head.sha }}\",\"status\":\"completed\",\"conclusion\":\"failure\",\"output\":{\"title\":\"Checklist Validation\",\"summary\":\"Please complete all checklist items before merging the pull request.\"}}"
          exit 1

  finalize:
    needs: enforce-checklist
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Check Status
        if: needs.enforce-checklist.outputs.invalidItems != 'true'
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/check-runs" \
            -d "{\"name\":\"Checklist\",\"head_sha\":\"${{ github.event.pull_request.head.sha }}\",\"status\":\"completed\",\"conclusion\":\"success\",\"output\":{\"title\":\"Checklist Validation\",\"summary\":\"All checklist items are checked.\"}}"
      - name: Update Check Status
        if: always()
        run: |
          exit 0

