# .github/workflows/enforce-checklist.yml
name: Enforce Checklist and Auto-Merge

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  enforce-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Required Checklist
        id: checklist
        run: |
          # Define the required checklist items
          required_items=("Are your changes following SOLID principles?" "Are there any erroneous console logs, debuggers or leftover code in your changes?" "Walk away, take a break, re-read what you filled out above does it make sense if you were coming in cold? What extra context could you provide?")
          
          # Get the PR number from GITHUB_REF
          pr_number=${GITHUB_REF#refs/pull/}
          pr_number=${pr_number%/merge}
          
          # Read the latest PR description using GitHub REST API
          pr_description=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" | jq -r .body)
          
          # Check if all required items are checked in the PR description
          invalid_items=false
          for item in "${required_items[@]}"; do
            if [[ ! "$pr_description" =~ "- [x] $item" ]]; then
              invalid_items=true
              echo "Unchecked checklist item: $item"
            fi
          done
          
          # Output the result to an environment file
          echo "INVALID_ITEMS=$invalid_items" >> $GITHUB_ENV
          if [[ "$invalid_items" == "true" ]]; then
            echo "Checklist validation failed. Please complete all checklist items before merging the pull request."
            exit 1
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finalize:
    needs: enforce-checklist
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Check Status
        if: always()
        run: |
          echo "::set-output name=status::success"
      - name: Auto-Merge Pull Request
        if: always() && needs.enforce-checklist.outputs.status == 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pr } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            if (pr.mergeable === true) {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              });
              console.log("Pull request merged successfully.");
            } else {
              console.log("Pull request cannot be merged automatically. Please resolve conflicts manually.");
            }
