# .github/workflows/enforce-checklist.yml
name: Enforce Checklist

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  enforce-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Required Checklist
        id: checklist
        run: |
          # Define the required checklist items
          required_items=("Are your changes following SOLID principles?" "Are there any erroneous console logs, debuggers or leftover code in your changes?" "Walk away, take a break, re-read what you filled out above does it make sense if you were coming in cold? What extra context could you provide?")
          
          # Read the PR description
          pr_description=$(jq -r .pull_request.body $GITHUB_EVENT_PATH)
          
          # Check if all required items are checked in the PR description
          invalid_items=false
          for item in "${required_items[@]}"; do
            if [[ ! "$pr_description" =~ "- [x] $item" ]]; then
              invalid_items=true
              echo "Unchecked checklist item: $item"
            fi
          done
          
          # Output the result
          echo "::set-output name=invalidItems::$invalid_items"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Check Status
        if: steps.checklist.outputs.invalidItems == 'true'
        run: |
          echo "::set-output name=status::failure"
        id: status

  finalize:
    needs: enforce-checklist
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Check Status
        if: needs.enforce-checklist.outputs.status != 'failure'
        run: |
          echo "::set-output name=status::success"
      - name: Update Check Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Checklist',
              head_sha: context.payload.pull_request.head.sha,
              status: ${{ needs.enforce-checklist.outputs.status }},
              conclusion: ${{ needs.enforce-checklist.outputs.status == 'success' && 'success' || 'failure' }},
              output: {
                title: 'Checklist Validation',
                summary: ${{ needs.enforce-checklist.outputs.status == 'success' && 'All checklist items are checked.' || 'Please complete all checklist items before merging the pull request.' }}
              }
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
